const options = [
    {value: "CSS", label: "CSS"},
    {value: "JavaScript", label: "JavaScript"},
    {value: "HTML", label: "HTML"},
    {value: "SQL", label: "SQL"},
    {value: "NoSQL", label: "NoSQL"},
    {value: "Python", label: "Python"},
    {value: "Java", label: "Java"},
    {value: "C++", label: "C++"},
    {value: "C#", label: "C#"},
    {value: "PHP", label: "PHP"},
    {value: "Ruby", label: "Ruby"},
    {value: "Swift", label: "Swift"},
    {value: "Kotlin", label: "Kotlin"},
    {value: "Rust", label: "Rust"},
    {value: "Go", label: "Go"},
    {value: "TypeScript", label: "TypeScript"},
    {value: "R", label: "R"},
    {value: "Scala", label: "Scala"},
    {value: "Perl", label: "Perl"},
    {value: "Haskell", label: "Haskell"},
    {value: "Julia", label: "Julia"},
    {value: "Clojure", label: "Clojure"},
    {value: "Elixir", label: "Elixir"},
    {value: "Dart", label: "Dart"},
    {value: "Lua", label: "Lua"},
    {value: "Erlang", label: "Erlang"},
    {value: "F#", label: "F#"},
    {value: "C", label: "C"},
    {value: "Objective-C", label: "Objective-C"},
    {value: "VBA", label: "VBA"},
    {value: "MATLAB", label: "MATLAB"},
    {value: "Groovy", label: "Groovy"},
    {value: "Visual Basic", label: "Visual Basic"},
    {value: "RPG", label: "RPG"},
    {value: "COBOL", label: "COBOL"},
    {value: "Fortran", label: "Fortran"},
    {value: "ABAP", label: "ABAP"},
    {value: "Delphi", label: "Delphi"},
    {value: "PL/SQL", label: "PL/SQL"},
    {value: "Ada", label: "Ada"},
    {value: "Lisp", label: "Lisp"},
    {value: "Transact-SQL", label: "Transact-SQL"},
    {value: "Logo", label: "Logo"},
    {value: "Scheme", label: "Scheme"},
    {value: "Prolog", label: "Prolog"},
    {value: "Smalltalk", label: "Smalltalk"},
    {value: "PostScript", label: "PostScript"},
    {value: "Bash", label: "Bash"},
    {value: "PowerShell", label: "PowerShell"}, 
    {value: "D", label: "D"},
    {value: "Apex", label: "Apex"},
    {value: "Crystal", label: "Crystal"},
    {value: "Dylan", label: "Dylan"},
    {value: "Forth", label: "Forth"},
    {value: "LabVIEW", label: "LabVIEW"},
    {value: "Ladder Logic", label: "Ladder Logic"},
    {value: "LiveScript", label: "LiveScript"},
    {value: "MQL4", label: "MQL4"},
    {value: "MQL5", label: "MQL5"},
    {value: "Objective-J", label: "Objective-J"},
    {value: "OpenEdge ABL", label: "OpenEdge ABL"},
    {value: "OpenSCAD", label: "OpenSCAD"},
    {value: "PL/I", label: "PL/I"},
    {value: "Processing", label: "Processing"},
    {value: "PureScript", label: "PureScript"},
    {value: "Q", label: "Q"},
    {value: "Racket", label: "Racket"},
    {value: "RPG", label: "RPG"},
    {value: "Rust", label: "Rust"},
    {value: "SAS", label: "SAS"},
    {value: "Solidity", label: "Solidity"},
    {value: "SQLPL", label: "SQLPL"},
    {value: "Standard ML", label: "Standard ML"},
    {value: "Stata", label: "Stata"},
    {value: "Tcl", label: "Tcl"},
    {value: "Turing", label: "Turing"},
    {value: "Verilog", label: "Verilog"},
    {value: "VHDL", label: "VHDL"},
    {value: "Visual Basic .NET", label: "Visual Basic .NET"},
    {value: "WebAssembly", label: "WebAssembly"},
    {value: "XQuery", label: "XQuery"},
    {value: "Zig", label: "Zig"},
    {value: "SAS", label: "SAS"},
    {value: "Zsh", label: "Zsh"},
];

export default options;