const mongoose = require("mongoose");

const { Schema } = mongoose;

const languageSchema = new Schema({
  language: {
    type: String,
    required: true,
    enum: [
      "CSS",
      "JavaScript",
      "HTML",
      "SQL",
      "NoSQL",
      "Python",
      "Java",
      "C++",
      "C#",
      "PHP",
      "Ruby",
      "Swift",
      "Kotlin",
      "Rust",
      "Go",
      "TypeScript",
      "R",
      "Scala",
      "Perl",
      "Haskell",
      "Julia",
      "Clojure",
      "Elixir",
      "Dart",
      "Lua",
      "Erlang",
      "F#",
      "Assembly",
      "C",
      "Objective-C",
      "VBA",
      "MATLAB",
      "Groovy",
      "Visual Basic",
      "RPG",
      "COBOL",
      "Fortran",
      "ABAP",
      "Delphi",
      "PL/SQL",
      "Ada",
      "Lisp",
      "Transact-SQL",
      "Logo",
      "Scheme",
      "Prolog",
      "Smalltalk",
      "PostScript",
      "Bash",
      "PowerShell",
      "D",
      "Apex",
      "Crystal",
      "Dylan",
      "Forth",
      "Julia",
      "LabVIEW",
      "Ladder Logic",
      "Ladder Logic",
      "LiveScript",
      "MQL4",
      "MQL5",
      "Objective-J",
      "OpenEdge ABL",
      "OpenSCAD",
      "PL/I",
      "PL/SQL",
      "Processing",
      "PureScript",
      "Q",
      "Racket",
      "RPG",
      "Rust",
      "SAS",
      "Solidity",
      "SQLPL",
      "Standard ML",
      "Stata",
      "Tcl",
      "Turing",
      "Verilog",
      "VHDL",
      "Visual Basic .NET",
      "WebAssembly",
      "XQuery",
      "Zig",
      "Zsh",
      "Other",
    ],
  },
  skill: {
    type: String,
    required: true,
    enum: [
      "Youngling",
      "Padawan",
      "Jedi Knight",
      "Jedi Master",
      "Council Member",
    ],
  },
});

const Language = mongoose.model("Language", languageSchema);

module.exports = Language;
